using Shared.Domain.DDD;

namespace AI.Domain.Entities
{
    /// <summary>
    /// Represents a user's preference embedding vector.
    /// Generated by aggregating embeddings of categories the user has interacted with.
    /// 
    /// STRATEGY: Weighted average of category embeddings based on user interest scores.
    /// This creates a "preference vector" that represents the user's taste in vector space.
    /// 
    /// USE CASES:
    /// 1. Find similar users (collaborative filtering)
    /// 2. Find similar categories (content-based filtering)
    /// 3. Cold-start mitigation (blend with global preferences)
    /// </summary>
    public class UserEmbedding : AggregateRoot<Guid>
    {
        public Guid UserId { get; private set; }

        /// <summary>
        /// The user's preference embedding vector
        /// Dimension: 384 for all-MiniLM-L6-v2 model
        /// </summary>
        public float[] Embedding { get; private set; } = default!;

        /// <summary>
        /// Dimension of the embedding vector
        /// </summary>
        public int Dimension { get; private set; }

        /// <summary>
        /// Number of category interactions used to build this embedding
        /// </summary>
        public int InteractionCount { get; private set; }

        /// <summary>
        /// Categories that contributed to this embedding
        /// </summary>
        private readonly List<string> _contributingCategories = new();
        public IReadOnlyCollection<string> ContributingCategories => _contributingCategories.AsReadOnly();

        /// <summary>
        /// When this embedding was last recalculated
        /// </summary>
        public DateTime LastCalculated { get; private set; }

        /// <summary>
        /// Confidence score (0-1) based on interaction count and recency
        /// </summary>
        public double Confidence { get; private set; }

        private UserEmbedding() { }

        // ===== FACTORY METHOD =====
        public static UserEmbedding Create(
            Guid userId,
            float[] embedding,
            List<string> contributingCategories)
        {
            if (userId == Guid.Empty)
                throw new ArgumentException("UserId cannot be empty.", nameof(userId));

            if (embedding == null || embedding.Length == 0)
                throw new ArgumentException("Embedding cannot be null or empty.", nameof(embedding));

            var now = DateTime.UtcNow;

            var entity = new UserEmbedding
            {
                Id = Guid.NewGuid(),
                UserId = userId,
                Embedding = embedding,
                Dimension = embedding.Length,
                InteractionCount = contributingCategories.Count,
                LastCalculated = now,
                CreatedAt = now,
                Confidence = CalculateConfidence(contributingCategories.Count, 0)
            };

            entity._contributingCategories.AddRange(contributingCategories);

            return entity;
        }

        // ===== UPDATE METHODS =====

        /// <summary>
        /// Recalculates the user embedding based on new category interactions
        /// </summary>
        /// <param name="categoryEmbeddings">Weighted category embeddings</param>
        /// <param name="weights">Weights for each category (based on user interest scores)</param>
        public void Recalculate(
            Dictionary<string, float[]> categoryEmbeddings,
            Dictionary<string, double> weights)
        {
            if (categoryEmbeddings == null || categoryEmbeddings.Count == 0)
                throw new ArgumentException("Category embeddings cannot be empty.", nameof(categoryEmbeddings));

            if (!categoryEmbeddings.Values.First().SequenceEqual(Embedding.Take(Dimension)))
            {
                // Verify all embeddings have the same dimension
                int expectedDim = categoryEmbeddings.Values.First().Length;
                if (categoryEmbeddings.Values.Any(e => e.Length != expectedDim))
                    throw new ArgumentException("All embeddings must have the same dimension.", nameof(categoryEmbeddings));
            }

            int dimension = categoryEmbeddings.Values.First().Length;
            var weightedEmbedding = new float[dimension];
            double totalWeight = 0;

            // Calculate weighted average of category embeddings
            foreach (var kvp in categoryEmbeddings)
            {
                string category = kvp.Key;
                float[] embedding = kvp.Value;
                double weight = weights.TryGetValue(category, out var w) ? w : 1.0;

                for (int i = 0; i < dimension; i++)
                {
                    weightedEmbedding[i] += (float)(embedding[i] * weight);
                }

                totalWeight += weight;
            }

            // Normalize by total weight
            if (totalWeight > 0)
            {
                for (int i = 0; i < dimension; i++)
                {
                    weightedEmbedding[i] /= (float)totalWeight;
                }
            }

            // Normalize vector (unit length for cosine similarity)
            double norm = Math.Sqrt(weightedEmbedding.Sum(x => x * x));
            if (norm > 0)
            {
                for (int i = 0; i < dimension; i++)
                {
                    weightedEmbedding[i] /= (float)norm;
                }
            }

            Embedding = weightedEmbedding;
            Dimension = dimension;
            _contributingCategories.Clear();
            _contributingCategories.AddRange(categoryEmbeddings.Keys);
            InteractionCount = _contributingCategories.Count;
            LastCalculated = DateTime.UtcNow;
            Confidence = CalculateConfidence(InteractionCount, 0);
        }

        /// <summary>
        /// Updates the embedding vector directly (e.g., from incremental learning)
        /// </summary>
        public void UpdateEmbedding(float[] newEmbedding)
        {
            if (newEmbedding == null || newEmbedding.Length == 0)
                throw new ArgumentException("Embedding cannot be null or empty.", nameof(newEmbedding));

            Embedding = newEmbedding;
            Dimension = newEmbedding.Length;
            LastCalculated = DateTime.UtcNow;
        }

        /// <summary>
        /// Applies time decay to confidence score
        /// </summary>
        public void ApplyConfidenceDecay(double halfLifeInDays = 7.0)
        {
            double daysElapsed = (DateTime.UtcNow - LastCalculated).TotalDays;
            double decayFactor = Math.Pow(0.5, daysElapsed / halfLifeInDays);
            Confidence *= decayFactor;
        }

        /// <summary>
        /// Calculates cosine similarity with another user embedding
        /// </summary>
        public double CosineSimilarity(UserEmbedding other)
        {
            if (other == null || other.Dimension != Dimension)
                return 0;

            double dotProduct = 0;
            double normA = 0;
            double normB = 0;

            for (int i = 0; i < Dimension; i++)
            {
                dotProduct += Embedding[i] * other.Embedding[i];
                normA += Embedding[i] * Embedding[i];
                normB += other.Embedding[i] * other.Embedding[i];
            }

            if (normA == 0 || normB == 0) return 0;

            return dotProduct / (Math.Sqrt(normA) * Math.Sqrt(normB));
        }

        /// <summary>
        /// Calculates cosine similarity with a category embedding
        /// </summary>
        public double CosineSimilarity(float[] categoryEmbedding)
        {
            if (categoryEmbedding == null || categoryEmbedding.Length != Dimension)
                return 0;

            double dotProduct = 0;
            double normA = 0;
            double normB = 0;

            for (int i = 0; i < Dimension; i++)
            {
                dotProduct += Embedding[i] * categoryEmbedding[i];
                normA += Embedding[i] * Embedding[i];
                normB += categoryEmbedding[i] * categoryEmbedding[i];
            }

            if (normA == 0 || normB == 0) return 0;

            return dotProduct / (Math.Sqrt(normA) * Math.Sqrt(normB));
        }

        /// <summary>
        /// Confidence calculation based on interaction count and recency
        /// </summary>
        private static double CalculateConfidence(int interactionCount, double daysElapsed)
        {
            // Sigmoid function for interaction count saturation
            double countFactor = 1.0 / (1.0 + Math.Exp(-0.5 * (interactionCount - 10)));

            // Time decay factor
            double timeFactor = Math.Pow(0.5, daysElapsed / 7.0);

            return Math.Min(1.0, countFactor * timeFactor);
        }

        protected override void Apply(IDomainEvent @event)
        {
            // Event sourcing hooks for: UserEmbeddingUpdated, UserEmbeddingCreated
        }
    }
}
