services:
  # Backend API
  backend-api:
    image: capstone-backend:latest
    build:
      context: .
      dockerfile: Backend/Api/Api/Dockerfile
    container_name: AIPromo-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=AIPromo;Username=postgres;Password=AIPromo123
      - Redis__Configuration=redis:6379,password=AIPromo123
      - RabbitMQ__Host=rabbitmq
    ports:
      - "5000:8080"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - aipromo-network

  # PostgreSQL Database
  postgres:
    image: postgres:17-alpine
    container_name: AIPromo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AIPromo123
      POSTGRES_DB: AIPromo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aipromo-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: AIPromo-redis
    restart: unless-stopped
    command: redis-server --requirepass AIPromo123 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - aipromo-network
  
  # Redis Web GUI
  redis-insight:
    image: redis/redisinsight:latest
    container_name: AIPromo-redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redis_insight_data:/data
    networks:
      - aipromo-network
    depends_on:
      - redis
  
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: AIPromo-rabbitmq
    restart: unless-stopped
    environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: admin
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq
    networks:
        - aipromo-network
        
  # MinIO
  minio:
     image: minio/minio:latest
     container_name: AIPromo-minio
     restart: unless-stopped
     environment:
        MINIO_ROOT_USER: minioadmin
        MINIO_ROOT_PASSWORD: minioadmin
     command: server /data --console-address ":9001"
     ports:
        - "9000:9000"
        - "9001:9001"
     volumes:
        - minio_data:/data
     networks:
        - aipromo-network

volumes:
  postgres_data:
  redis_data:
  redis_insight_data:
  rabbitmq_data:
  minio_data:

networks:
  aipromo-network:
    driver: bridge